#import "../templates/prelude.typ": *

== Conclusion

Après une rapide histoire des mariages stables, j'ai présenté les bases nécessaires au maniement des préférences acycliques : le vocabulaire spécifique (parfois imagé), le formalisme, le grand théorème d'_existence, unicité, convergence_ et une description des principales classes de préférences acycliques, comme les préférences globales ou géométriques.

J'ai ensuite détaillé la propriété d'auto-stabilisation, et plus précisément le temps nécessaire pour une convergence complète. J'ai présenté des techniques qui permettent de borner ou d'estimer ce temps pour certains paramètres particuliers, et j'ai proposé l'utilisation de simulations pour mettre en évidence le rôle joué par chaque paramètre. On retiendra que dans le pire des cas, avec des pairs asynchrones, la convergence peut être très longue, alors qu'en pratique, elle est assez rapide (préférences globales), voire très rapide (la plupart des autres préférences).

Enfin, j'ai décrit la distribution des partenaires stables pour quelques classes de préférences, en proposant une analyse de cette distribution sous des hypothèses d'indépendance, puis en validant et étendant ces résultats numériquement. Pour les préférences globales, j'ai ainsi mis en évidence l'effet de _stratification_. De manière imagée, dans un monde où il n'y aurait qu'un unique critère de beauté, les beaux se retrouvent avec les beaux, et les moches n'ont guère d'autre choix que d'être avec les moches#footnote[Dans la même veine, je conseille l'article _Beauty and distance in the stable marriage problem_, qui pimente l'algorithme du bal en étudiant l'effet de l'introduction d'un critère de beauté @caldarelli01beauty.].

Pour les préférences géométriques, c'est une petit-mondisation qui se produit, due au fait que la distribution des partenaires est en aile lourde, ce qui assure à la fois la localité et les liens longs. L'image est celle d'un monde régi par l'homophilie (_qui se ressemble s'assemble_) : la plupart du temps, la réciprocité permet des collaborations entre proches, mais quand un pair est rejeté par ses plus proches voisins, il doit chercher de plus en plus loin, chez des partenaires potentiels qui l'apprécient de moins en moins au fur et à mesure qu'il doit s'éloigner de sa propre position.

Au final, j'espère avoir réussi à faire partager ma conception des réseaux à préférences acycliques : un modèle possible pour les réseaux pair-à-pair, un ensemble varié de petits problèmes mathématiques, mais aussi une informatique récréative. Je suis conscient que ce chapitre pose plus de questions qu'il n'apporte de réponses : modélisation de l'initiative aléatoire, de l'agitation, étude de nouvelles préférences (pourquoi pas cycliques), graphes et quotas arbitraires, voire variables, routage dans les petits-mondes géométriques… Je n'aurais assurément ni le temps, ni les facultés de répondre à tous ces problèmes, et en conséquent, si ce chapitre donne l'envie à au moins un lecteur de s'intéresser aux réseaux à préférences acycliques, je pense qu'il aura parfaitement rempli son rôle.

Pour ma part, je pense dans le futur essayer d'appliquer les réseaux à préférences à des situations pratiques, et les relier aux travaux que j'ai effectué sur les problématiques de la distribution. J'estime que les préférences acycliques commencent à avoir la maturité nécessaire pour apporter un éclairage nouveau à ces problèmes, et j'aimerais le vérifier, comme j'en parle dans le prochain et dernier chapitre.
