= Synthesis and perspectives <ch:conclusion>

I have presented over the course of these few pages my own point of view on this new research domain that is peer-to-peer. Starting from an original definition that has the advantage of highlighting why peer-to-peer is a research domain, I have proposed a classification that allows describing, in broad strokes, the different themes that can be addressed, depending on whether one considers the problem of localization or distribution; whether one approaches it using an explicit or implicit structure; whether one places the decision at the sending end, the receiving end, or both sides; whether one takes an initial theoretical or empirical approach.

I then placed my own contributions within these themes: while one part of my work falls within the framework of a better understanding of the problems related to broadcasting, while opening the way to future and promising applications, another part is dedicated to creating a new model that brings a different perspective on the dynamics of self-structured systems in general, and of peer-to-peer in particular.

I have not discussed at all my work done in continuation of my thesis topic, PageRank @bouklit05backrank @mathieu06local @djungu06etude @djungu08speedsiterank @gaume08random @gaume09pagerank, because although dealing with a related subject, large graphs, it does not strictly fall within the scope of peer-to-peer, and it is not my main subject of study at present. Nevertheless, it is not impossible that a new stroke of chance might one day lead me to discover new themes related to this subject and completely rekindle my interest.

To return to the subject of peer-to-peer, I would like to insist one last time on the fact that the different themes are neither fixed nor compartmentalized, and that if this makes the classification of research more analog than dichotomous, I think that this is _in fine_ beneficial. For example, certain graphs, such as de Bruijn graphs, were introduced in peer-to-peer in order to build DHTs @fraigniaud06d2b. Later, these same graphs escaped the localization problem and were used to propose broadcast structures @prefixstream. Similarly, epidemic techniques, which are by nature broadcasting techniques, can have utility in localization @epitella. Over the years, this porosity thus allows advancing the research front, and I like to believe that this is far from over.

For all these exchanges correspond perfectly with the philosophy I have adopted as a researcher, and my intuition tells me that by remaining attentive to the innovations and mutations occurring in all these themes, I have chances of discovering new leads that will awaken my curiosity. There are some on which I have a certain idea, and I would like to conclude this thesis by presenting these few directions on which I plan to work in the medium term, knowing that it is always possible that tomorrow, a new encounter provokes a new direction in my research.

== Preference networks

As the reader will have realized, the subject of preference networks is close to my heart, and I think it should still occupy a part of my work for some time yet. The road that remains to be traveled is indeed at least as long, and I believe just as fascinating, as the one that has already been covered: finer characterization of self-stabilizing properties, modeling of dynamic graphs and quotas, study of routing properties, return to cyclic preferences... I hope, by continuing to promote it within the scientific community, to succeed in evangelizing researchers who in turn will advance the theory while developing concrete applications.

On the front of these concrete applications, I believe that it should be possible to use the model to design even more efficient epidemic broadcast algorithms. Indeed, as I have shown, global preferences allow selection by bandwidth, and recent work seems to point to bandwidth-oriented selection as promising for achieving epidemic broadcast among peers with heterogeneous capacities. Similarly, the results obtained on latency preferences allow hoping for a minimization of the network impact of broadcasting without affecting the properties of the broadcast graph. By combining these two types of preferences in the right way and applying the result to epidemic broadcasting, the final algorithm has a good chance of being very efficient.

Beyond peer-to-peer, I also hope to discover new things by looking at whether preference networks can have a connection with sensor networks, which I plan to investigate. This shift in theme will I think be beneficial for preference networks, and who knows perhaps also for sensor networks.

== Prototypes

It is a fact, I am not a developer. Nevertheless, I find it extremely frustrating to have worked on concepts and algorithms without being able to verify whether they hold up in practice. If I want to be consistent with my positioning as a researcher, I therefore think that I owe it to myself to try to push the work that can be pushed as far as possible along the path to application, perhaps even to deployment. This is of course a task that I am unable to accomplish alone, and I especially hope to convince specialists in the field to carry out the development.

At present, there are two prototypes that I would appreciate having at my disposal in order to be able to test _in the field_ and improve the algorithms on which I have worked so far. It is not very difficult to guess which ones: an epidemic broadcast prototype, and a video-on-demand prototype.

== Future of peer-to-peer

To conclude on a more general direction, I would like to share my opinion on the future of peer-to-peer. For if peer-to-peer must evolve, research will have to adapt as well, this including my own work.

Let us return for a moment to the origins of the _golden age_ of peer-to-peer, as I described them in the introduction: from a social standpoint, the explosion of peer-to-peer was triggered by the need to provide a service for which demand exists (a consequence of technical progress and the Internet bubble), but not the supply (bursting of the bubble). But today, services are once again being offered: storage spaces, file sharing and commerce or multimedia content, television and video recorder on the Internet... Thanks to superior ergonomics, these services tend to regain ground from peer-to-peer as a social phenomenon. The real stake of this battle is the localization of resources, at the user's end (peer-to-peer) or on servers (Google, to simplify). The outcome is still uncertain, with victories and defeats on both sides. What is certain is that we are in a transitional situation and that current uses, particularly peer-to-peer uses, are doomed to evolve or wither.

But _in fine_, there will always be on one side services to provide, and on the other resources, whether on a PC, a phone, a virtual video recorder, a set-top box, a proxy, or a cloud of servers. With the multiplication of platforms, on the user side or the provider side, there is therefore a question that, in my opinion, will remain relevant no matter what happens: _who retrieves what from whom?_ And if I am asked my opinion on the future of peer-to-peer (and therefore incidentally on that of research on the subject), I bet on its foreseeable metempsychosis into future technologies, whatever they may be. In other words, while it is possible that peer-to-peer, in its BitTorrent-esque understanding, may end up disappearing in the coming years, peer-to-peer research, which consists of answering the question _who retrieves what from whom?_ when it is not trivial, still has a bright future ahead. The name may change after absorption by a new emerging domain (Cloud Computing? Virtualization?) but I believe that the spirit, themes, and methods of the domain will survive the transition. However, this does not mean either that the domain should not anticipate its own evolution. Some of these directions are moreover already visible: appearance of new services that pose new challenges, for example _start-over_ which combines slightly delayed and on-demand broadcast; growing heterogeneity of available resources, with the appearance of hybrid solutions and the multiplication of platforms; shifting of bottlenecks related to changes in the network and usage patterns.
