= Synthèse et perspectives <ch:conclusion>

J'ai présenté au cours de ces quelques pages le point de vue qui est le mien sur ce nouveau domaine de recherche qu'est le pair-à-pair. Partant d'une définition originale qui a l'avantage de mettre en avant pourquoi le pair-à-pair est un domaine de recherche, j'ai proposé une classification qui permet de décrire, dans les grandes lignes, les différents thèmes qu'il est possible d'aborder, suivant que l'on considère le problème de la localisation ou de la distribution ; qu'on l'aborde à l'aide d'une structure explicite ou implicite ; qu'on place la décision à l'émission, à la réception ou des deux côtés ; qu'on ait une approche initiale théorique ou empirique.

J'ai ensuite placé mes propres contributions au sein de ces thématiques : alors qu'une partie de mes travaux s'inscrit dans le cadre d'une meilleure compréhension des problèmes liés à la diffusion, tout en ouvrant la voie à de futures et prometteuses applications, une autre partie est consacrée à créer un nouveau modèle permettant d'apporter un autre éclairage sur les dynamiques des systèmes auto-structurés en général, et du pair-à-pair en particulier.

Je n'ai pas du tout parlé de mes travaux faits en continuité de ma thématique de thèse, le PageRank @bouklit05backrank @mathieu06local @djungu06etude @djungu08speedsiterank @gaume08random @gaume09pagerank, car bien que traitant d'un sujet proche, les grands graphes, ils ne rentrent pas à proprement parler dans le cadre du pair-à-pair, et ce n'est pas mon principal sujet d'étude à l'heure actuelle. Néanmoins, il n'est pas impossible qu'un nouvel hasard me fasse un jour découvrir des nouvelles thématiques liées à ce sujet et relance complètement mon intérêt.

Pour revenir au sujet du pair-à-pair, j'aimerais insister une dernière fois sur le fait que les différentes thématiques ne sont pas figées ni cloisonnées, et que si cela rend la classification des recherches plus analogique que dichotomique, je pense que cela est _in fine_ bénéfique. Par exemple, certains graphes, comme les graphes de de Bruijn, ont été introduits en pair-à-pair afin de réaliser des DHTs @fraigniaud06d2b. Plus tard, ces mêmes graphes se sont échappés du problème de la localisation et ont été utilisés pour proposer des structures de diffusion @prefixstream. De même, les techniques épidémiques, qui sont par nature des techniques de diffusion, peuvent avoir une utilité en localisation @epitella. Au fil des ans, cette porosité permet ainsi de faire progresser le front de la recherche, et j'aime à croire que cela est loin d'être terminé.

Car tous ces échanges correspondent parfaitement à la philosophie que j'ai adopté en tant que chercheur, et mon intuition me dit qu'en restant à l'écoute des innovations et des mutations qui se produisent dans tous ces thèmes, j'ai des chances de découvrir de nouvelles pistes qui éveilleront ma curiosité. Il y en a certaines sur lesquelles j'ai une certaine idée, et j'aimerais conclure ce mémoire en exposant ces quelques axes sur lesquels je pense travailler à moyen terme, sachant qu'il est toujours possible que demain, une nouvelle rencontre provoque une nouvelle orientation de mes recherches.

== Réseaux à préférences

Comme le lecteur s'en sera rendu compte, le sujet des réseaux à préférences me tient à coeur, et je pense qu'il devrait encore occuper une partie de mes travaux pour quelques temps encore. Le chemin qu'il reste à parcourir est en effet au moins aussi long, et je le pense aussi passionnant, que celui qui a déjà été fait : caractérisation plus fine des propriétés auto-stabilisantes, modélisation des graphes et quotas dynamiques, étude des propriétés de routage, retour aux préférences cycliques... J'espère, en continuant d'en faire la promotion au sein de la communauté scientifique, réussir à évangéliser des chercheurs qui à leur tour feront progresser la théorie tout en développant des applications concrètes.

Sur le front de ces applications concrètes, j'estime qu'il doit être possible d'utiliser le modèle afin de concevoir des algorithmes de diffusion épidémique encore plus performants. En effet, comme je l'ai montré, les préférences globales permettent une sélection par la bande passante, et des travaux récents semble désigner la sélection orientée par la bande passante comme prometteuse pour réaliser une diffusion épidémique au sein de pairs de capacités hétérogènes. De même, les résultats obtenus sur les préférences de latences permettent d'espérer une minimisation de l'impact réseau de la diffusion sans affecter les propriétés du graphe de diffusion. En combinant de la bonne manière ces deux types de préférences et en appliquant le résultat à la diffusion épidémique, l'algorithme final a de bonnes chances d'être très efficace.

Au-delà du pair-à-pair, j'espère aussi découvrir de nouvelles choses en regardant si les réseaux à préférences peuvent avoir un lien avec les réseaux de capteurs, sur lesquels je compte me pencher. Ce glissement de thématique sera je pense bénéfique pour les réseaux à préférences, et qui sait peut-être aussi pour les réseaux de capteurs.

== Prototypes

C'est un fait, je ne suis pas un développeur. Malgré tout, je trouve extrêmement frustrant d'avoir travaillé sur des concepts et des algorithmes sans pouvoir vérifier s'ils tiennent la route en pratique. Si je veux être en accord avec mon positionnement en tant que chercheur, je pense donc que je me dois d'essayer de pousser les travaux qui peuvent l'être le plus loin possible sur le chemin de l'application, pourquoi pas jusqu'au déploiement. C'est bien sûr une tâche que je suis incapable de réaliser seul, et j'espère surtout arriver à convaincre des spécialistes du domaine de réaliser le développement.

À l'heure actuelle, il existe deux prototypes que j'apprécierais d'avoir à ma disposition afin de pouvoir tester _grandeur nature_ et améliorer les algorithmes sur lesquels j'ai travaillé jusqu'à présent. Il n'est pas très difficile de deviner lesquels : un prototype de diffusion épidémique, et un prototype de vidéo-à-la-demande.

== Futur du pair-à-pair

Pour conclure sur un axe plus général, j'aimerais partager mon opinion sur le devenir du pair-à-pair. Car si le pair-à-pair doit évoluer, la recherche devra s'adapter elle aussi, ceci incluant mes propres travaux.

Revenons un instant aux origines de l'_âge d'or_ du pair-à-pair, telles que je les ai décrites dans l'introduction : d'un point de vue social, l'explosion du pair-à-pair a été provoqué par le besoin de fournir un service pour lequel la demande existe (conséquence des progrès techniques et de la bulle Internet), mais pas l'offre (éclatement de la bulle). Mais aujourd'hui, les services sont à nouveau offerts : espaces de stockage, partage et commerce de fichiers ou de contenus multimedia, télévision et magnétoscope sur Internet... Grâce à une ergonomie supérieure, ces services tendent à reprendre du terrain sur le pair-à-pair en tant que phénomène de société. Le véritable enjeu de cette bataille est la localisation des ressources, chez l'usager (pair-à-pair) ou sur des serveurs (Google, pour simplifier). L'issue en est encore incertaine, avec des victoires et des défaites de part et d'autre. Ce qui est sûr, c'est que nous sommes dans une situation transitoire et que les usages actuels, en particulier les usages pair-à-pair, sont condamnés à évoluer ou à dépérir.

Mais _in fine_, il y a aura toujours d'un côté des services à fournir, et de l'autre des ressources, fussent-elles sur un PC, un téléphone, un magnétoscope virtuel, un adjoint de poste de télévision, un proxy ou un nuage de serveurs. Avec la multiplication des supports, côté usager ou côté fournisseur, il y a donc une question qui, à mon avis, va rester d'actualité quoi qu'il arrive : _qui récupère quoi de la part de qui ?_ Et si l'on me demande mon avis sur l'avenir du pair-à-pair (et donc accessoirement sur celui des recherches sur le sujet), je mise sur sa prévisible métempsychose dans les technologies à venir, quelles qu'elles soient. Autrement dit, s'il est possible que le pair-à-pair, dans sa compréhension bittorrentesque, finisse par disparaître dans les années à venir, la recherche en pair-à-pair, qui consiste à répondre à la question _qui récupère quoi de la part de qui ?_ quand elle n'est pas triviale, a encore de beaux jours devant elle. L'appellation changera peut-être après absorption par un nouveau domaine émergeant (Cloud Computing ? Virtualisation ?) mais je crois que l'esprit, les thématiques et les méthodes du domaine survivront à la transition. Cependant, cela ne veut pas dire non plus que le domaine ne doit pas anticiper sa propre évolution. Certaines de ces directions sont d'ailleurs déjà visibles : apparition de nouveaux services qui posent de nouveaux défis, par exemple le _start-over_ qui combine diffusion en léger différé et à la demande ; hétérogénéité croissante des ressources disponibles, avec l'apparition de solutions hybrides et la multiplication des supports ; déplacement des goulots d'étranglement lié aux changements dans le réseau et les usages.
