= Positionnement <ch:positionnement>

S'il apparaît clairement, au travers de mes travaux, que ma principale thématique de recherche est le pair-à-pair, je suis conscient qu'il n'est pas forcément évident d'identifier le fil conducteur qui unifie mon travail, même si les concepts de distribution et d'auto-structure apparaissent souvent dans le cadran de la boussole : dimensionnement générique de la distribution avec la loi de conservation de la bande passante @benbadis08playing ; distribution épidémique en léger différé, c'est-à-dire auto-structurée et pull @bonald08epidemic ; distribution décentralisée de vidéo-à-la-demande (auto-structurée, avec une phase push et une phase pull) ; modélisation d'auto-structure avec l'ensemble de mes travaux sur les réseaux à préférences @mathieu09acyclic.

Afin de mieux comprendre mon parcours, voici les trois qualités que j'essaie de réunir autant que possible lorsque je pratique la recherche. Je tiens bien sûr à préciser que ce ne sont en aucun cas les qualités qui définissent un bon chercheur d'une manière générale, car je pense que chaque chercheur a son propre profil, sa propre personnalité, et donc ses propres qualités à développer afin de s'épanouir sur le plan professionnel.

/ Curiosité: J'aime découvrir de nouvelles thématiques. Qui plus est, j'apprécie particulièrement lorsque les sujets que j'attaque n'ont pas encore été étudiés, ou très peu. En effet, cette curiosité me pousse souvent à déborder ou dévier de mes intentions initiales, et j'ai toujours la crainte, quand je découvre des résultats que je trouve nouveaux et intéressants, de découvrir par la suite que ces résultats sont connus depuis longtemps. C'est pourquoi, après un doctorat dont le sujet était le PageRank de Google, sujet d'actualité à l'époque, je me suis tourné quasi-naturellement vers les thématiques émergentes du pair-à-pair, mais en privilégiant la modélisation de la distribution, sujet relativement peu abordé à l'époque compte tenu de son importance.

/ Écoute: Je suis un partisan du discontinuisme scientifique, dans le sens où je ne crois pas que la science évolue selon une progression continue, maîtrisée et quantifiable, mais au contraire qu'elle est la somme de ruptures abruptes. À une plus modeste échelle, qui est la mienne, j'applique cette théorie en m'efforçant de repérer les micro-ruptures qui peuvent passer à ma portée : j'écoute et j'observe, sautant sur l'occasion d'explorer de nouvelles pistes, issues de mon domaine, d'autres domaines, voire de ma sphère privée. L'exemple le plus extrême est celui de la naissance des réseaux à préférences acycliques, relaté dans l'avant-propos, mais la plupart des autres thématiques que j'ai étudiées sont aussi basées sur l'écoute et l'observation des autres. Ainsi, mes déboires personnels de téléchargement en pair-à-pair m'ont amené à étudier les mécanismes de diffusion dans la distribution de fichiers @mathieu06missing. Quelques années plus tard, écoutant un exposé de Laurent Massoulié, j'ai réalisé que ce que j'avais fait présentait beaucoup de ressemblances avec la diffusion épidémique, ce qui m'a poussé à explorer cette thématique.

/ Intuition: Enfin, je suis incapable de travailler sur un sujet sans en avoir une compréhension intuitive forte, soit initiale, soit acquise au cours des travaux préliminaires. C'est d'ailleurs autant un défaut qu'une qualité. C'est une qualité car l'intuition rend les choses simples, et facilite la communication de l'essence de ses travaux aux autres. Elle permet de présenter son sujet en escamotant les difficultés techniques, le rendant plus attrayant. C'est un défaut quand les idées qu'elles donnent dépassent la possibilité de les traiter proprement#footnote["Le succès c'est 1 % d'inspiration et 99 % de transpiration !", _Albert EINSTEIN_]. Faute de temps et de compétence technique adéquate, je traîne ainsi dans mes placards un certain nombre de conjectures dont je _sens_ qu'elles sont vraies sans arriver à les résoudre.

Enfin, j'aimerais discuter du positionnement de ma recherche sur le curseur qui va de la théorie (comprendre) à la pratique et à l'empirique (faire). S'il fallait me placer dans l'absolu, ce qui est discutable, j'estime que la recherche que je mène se positionne principalement à un niveau théorique. Personnellement, et à cause de mon parcours à la frontière de l'académie et de l'industrie, je préfère me considérer comme un intermédiaire. C'est une situation agréable lorsqu'elle permet d'apporter un éclairage théorique à un phénomène concret ou de transformer une équation en application concrète. Elle l'est moins lorsque je réalise à quel point mes compétences individuelles, prises séparément, sont faibles comparées aux ténors de chaque _camp_. Mes compétences en programmation ne me permettent guère d'aller au-delà du stade de la simulation, et ma trousse à outils mathématiques est moins fournie que celle de bien des chercheurs que je connais. Mais j'ai pris le parti de tourner ce que je considère comme une faiblesse personnelle en avantage, et plutôt que de chercher une compétition que je suis sûr de perdre dans les deux domaines de la théorie et de la pratique, je préfère me voir comme un passeur entre deux mondes qui idéalement devraient n'en former qu'un.

== Organisation du mémoire

Ce mémoire est structuré en trois chapitres. Le @ch:distribution s'intéresse aux travaux que j'ai menés autour du problème de la distribution de contenu. C'est un chapitre de synthèse, où j'essaie de donner les idées principales de ces travaux, articulées autour de trois sous-thèmes : la loi de la bande passante (dimensionner), la diffusion épidémique (simplifier), la vidéo-à-la-demande (décentraliser).

Vient ensuite le coeur de ce mémoire, le @ch:pbs, qui expose mes travaux sur les réseaux à préférences acycliques. En écrivant ce mémoire, j'avais une volonté très forte de donner une vision globale et unifiée de ce domaine que j'ai découvert il y a maintenant un peu plus de trois ans, c'est pourquoi j'y suis un peu plus exhaustif que pour un simple chapitre de synthèse.

Je termine naturellement par un chapitre conclusif, qui a pour but de replacer mes travaux dans le contexte du P2P à la fois au sens où je l'ai défini, mais aussi dans sa compréhension courante. De cette synthèse ressortent les futurs axes de recherche qui de mon point de vue méritent d'être étudiés afin de pouvoir appréhender pleinement les évolutions à venir autour de la philosophie P2P.
