= Positioning <ch:positionnement>

While it appears clearly, through my work, that my main research theme is peer-to-peer, I am aware that it is not necessarily easy to identify the common thread that unifies my work, even though the concepts of distribution and self-structure frequently appear in the compass quadrant: generic dimensioning of distribution with the bandwidth conservation law @benbadis08playing; epidemic broadcast with slight delay, that is, self-structured and pull @bonald08epidemic; decentralized video-on-demand distribution (self-structured, with a push phase and a pull phase); self-structure modeling with all of my work on preference networks @mathieu09acyclic.

In order to better understand my journey, here are the three qualities that I try to bring together as much as possible when I conduct research. I want to emphasize that these are by no means the qualities that define a good researcher in general, because I believe that each researcher has their own profile, their own personality, and therefore their own qualities to develop in order to thrive professionally.

/ Curiosity: I enjoy discovering new themes. Moreover, I particularly appreciate when the subjects I tackle have not yet been studied, or very little. Indeed, this curiosity often pushes me to go beyond or deviate from my initial intentions, and I always fear, when I discover results that I find new and interesting, subsequently discovering that these results have been known for a long time. This is why, after a doctoral thesis whose subject was Google's PageRank, a topic of current interest at the time, I turned quasi-naturally towards the emerging themes of peer-to-peer, but favoring the modeling of distribution, a subject relatively little addressed at the time given its importance.

/ Listening: I am a proponent of scientific discontinuism, in the sense that I do not believe that science evolves according to a continuous, controlled, and quantifiable progression, but rather that it is the sum of abrupt breaks. At a more modest scale, which is mine, I apply this theory by striving to spot the micro-breaks that may come within my reach: I listen and I observe, seizing the opportunity to explore new leads, stemming from my field, other fields, or even my private sphere. The most extreme example is that of the birth of acyclic preference networks, recounted in the foreword, but most of the other themes I have studied are also based on listening to and observing others. Thus, my personal downloading woes in peer-to-peer led me to study the broadcasting mechanisms in file distribution @mathieu06missing. A few years later, listening to a talk by Laurent Massoulie, I realized that what I had done bore many resemblances to epidemic broadcasting, which pushed me to explore this theme.

/ Intuition: Finally, I am unable to work on a subject without having a strong intuitive understanding of it, either initial or acquired during preliminary work. This is as much a weakness as a quality. It is a quality because intuition makes things simple, and facilitates communicating the essence of one's work to others. It allows one to present one's subject while glossing over the technical difficulties, making it more attractive. It is a weakness when the ideas it gives exceed the possibility of treating them properly#footnote["Success is 1% inspiration and 99% perspiration!", _Albert EINSTEIN_]. Due to lack of time and adequate technical competence, I thus carry in my closets a certain number of conjectures that I _feel_ are true without being able to prove them.

Finally, I would like to discuss the positioning of my research on the slider that goes from theory (understanding) to practice and the empirical (doing). If I had to place myself in absolute terms, which is debatable, I estimate that the research I conduct is positioned primarily at a theoretical level. Personally, and because of my career at the boundary between academia and industry, I prefer to consider myself as an intermediary. This is a pleasant situation when it allows bringing a theoretical perspective to a concrete phenomenon or transforming an equation into a concrete application. It is less pleasant when I realize how weak my individual skills, taken separately, are compared to the leading figures of each _camp_. My programming skills barely allow me to go beyond the simulation stage, and my mathematical toolkit is less well-stocked than that of many researchers I know. But I have decided to turn what I consider a personal weakness into an advantage, and rather than seeking a competition that I am sure to lose in both domains of theory and practice, I prefer to see myself as a bridge between two worlds that ideally should form only one.

== Organization of the thesis

This thesis is structured in three chapters. @ch:distribution focuses on the work I have conducted around the problem of content distribution. It is a synthesis chapter, where I try to present the main ideas of this work, articulated around three sub-themes: the bandwidth law (dimensioning), epidemic broadcasting (simplifying), video-on-demand (decentralizing).

Next comes the heart of this thesis, @ch:pbs, which presents my work on acyclic preference networks. In writing this thesis, I had a very strong desire to give a global and unified vision of this domain that I discovered a little over three years ago, which is why I am somewhat more exhaustive here than for a simple synthesis chapter.

I naturally conclude with a concluding chapter, whose purpose is to place my work in the context of P2P both in the sense in which I have defined it, and in its common understanding. From this synthesis emerge the future research directions that in my view deserve to be studied in order to fully grasp the forthcoming evolutions around the P2P philosophy.
